### ISSUE TITLE
Basic example not working on raspberry pi pico

### ISSUE THREAD

**Issue by iliquifysnacks** [mcauser/micropython-mpr121#2]
I'm new to micropython and hope this is not an obvious error on my part. I've been trying to get the minimal example to work with the Raspberry Pi Pico but I get the following error message: 

`Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "mpr121.py", line 79, in __init__
  File "mpr121.py", line 96, in reset
  File "mpr121.py", line 84, in _register8
OSError: [Errno 5] EIO`

The slightly altered example code I'm using looks like this:

```
from machine import I2C, Pin
import mpr121
import time

i2c = I2C(0, scl=Pin(9), sda=Pin(8), freq=100000)

time.sleep_ms(100)

mpr = mpr121.MPR121(i2c, 0x5A)

while True:
	print(mpr.touched())
	time.sleep_ms(100)
```

Could this issue be caused by the driver?

**Comment by iliquifysnacks** [comment]
Caused by broken jumper wire
